### ISSUE TITLE
[Bug] Getting huge numbers of ProbeWarnings

### ISSUE THREAD

**Issue by haiwu** [container-registry/helm-charts-oci-proxy#10]
Getting huge number of ProbeWarnings like this: 
Liveness probe warning: Probe terminated redirects, Response body: <a href="https://container-registry.com/helm-charts-oci-proxy/">Found</a>. 

This seems to be due to livenessProbe and readinessProbe pointing to '/', which being redirected to "https://container-registry.com/helm-charts-oci-proxy/", which ends up to be 404 not found.

**Comment by tpoxa** [comment]
Thanks @haiwu . In the latest version of the helm chart, I use `api/version` route for both probes.

Please check

```
helm template test oci://8gears.container-registry.com/library/helm-charts-oci-proxy
```

**Comment by haiwu** [comment]
Perfect! Thanks @tpoxa . Just tested ok with the new helm chart release 1.2.2. No more ProbeWarnings seen.
