### ISSUE TITLE
Public registry proxy not getting the latest Chart versions anymore?

### ISSUE THREAD

**Issue by PoliM** [container-registry/helm-charts-oci-proxy#3]
Hello everybody

Thanks for the proxy - great idea :-) I was using the public registry proxy and just wanted to update an Argo CD deployment when I found, that the registry does not have the latest Charts available (I know this might not be the right place to ask, but I didn't see another way to get in touch with you - sorry about that).

When I do `helm fetch oci://chartproxy.container-registry.com/argoproj.github.io/argo-helm/argo-cd` it downloads the version 5.42.1 even though the latest is 5.45.0
So I tried `helm fetch oci://chartproxy.container-registry.com/argoproj.github.io/argo-helm/argo-cd --version 5.45.0` and it returns "Error: chartproxy.container-registry.com/argoproj.github.io/argo-helm/argo-cd:5.45.0: not found".

I checked the tag list here https://chartproxy.container-registry.com/v2/argoproj.github.io/argo-helm/argo-cd/tags/list and it is not listed. 

Maybe you could give it a nudge? Anyway, thanks again for the service.

**Comment by Vad1mo** [comment]
I restarted the service. and that latest indey.yaml is now fetched. 
We do cache the upstream index.yaml file, but it seems there is a timing issue, or that a new index.yaml file is fetched on a 404.

This seems to be a bug to me.

maybe @tpoxa can look into that.

**Comment by PoliM** [comment]
Wow, that was quick, thanks a lot :-)

**Comment by jonasrutishauser** [comment]
It seems that it is out of date again.
